kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: builtin-podspecable-binding
  labels:
    eventing.knative.dev/release: "v0.18.0"
    duck.knative.dev/podspecable: "true"
# Do not use this role directly. These rules will be added to the "podspecable-binding role.
rules:
- # To patch the subjects of our bindings
  apiGroups:
  - "apps"
  resources:
  - "deployments"
  - "daemonsets"
  - "statefulsets"
  - "replicasets"
  verbs:
  - "list"
  - "watch"
  - "patch"
- apiGroups:
  - "batch"
  resources:
  - "jobs"
  verbs:
  - "list"
  - "watch"
  - "patch"
