apiVersion: v1
kind: Service
metadata:
  labels:
    eventing.knative.dev/release: "v0.18.0"
    role: eventing-webhook
  name: eventing-webhook
  namespace: knative-eventing
spec:
  ports:
  - name: https-webhook
    port: 443
    targetPort: 8443
  selector:
    role: eventing-webhook
