kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-bindings-namespaced-admin
  labels:
    eventing.knative.dev/release: "v0.18.0"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups: ["bindings.knative.dev"]
  resources: ["*"]
  verbs: ["*"]