kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-eventing-namespaced-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    eventing.knative.dev/release: "v0.18.0"
rules:
- apiGroups: ["eventing.knative.dev", "messaging.knative.dev", "sources.knative.dev",
    "flows.knative.dev", "bindings.knative.dev"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
